name: Build Kernel

on: 
  workflow_dispatch:
    inputs:
      ZIP_NAME:
        description: 'Final zip file output'
        required: true
        default: ''
      DEVICE_NAME:
        description: 'Your device codename.'
        required: true
        default: ''
      ANDROID_VERSION:
        description: 'Your android version.'
        required: true
        default: 't-oss'
        type: choice
        options:
        - t-oss
        - s-oss
        - r-oss
        - q-oss

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Start Building Kernel
      run: |
        export KBUILD_BUILD_USER="${{ github.actor }}"
        export KBUILD_BUILD_HOST="${{ github.event.inputs.DEVICE_NAME }}"
        ./build

    - name: Set Properties
      id: props
      run: |
        echo "date=$(TZ=Asia/Manila date +%Y%m%d-%I%M%p)" >> $GITHUB_OUTPUT

    - name: Compressed as Archive
      run: |
        cd /home/runner/work/myKernel/
        git clone --depth=1 https://github.com/cd-Seraph/AnyKernel3.git -b master AnyKernel
        cp out/arch/arm64/boot/Image AnyKernel
        python scripts/dtc/libfdt/mkdtboimg.py create AnyKernel/dtbo.img --page_size=4096 out/arch/arm64/boot/dts/vendor/oplus_7325/yupik-21643-overlay.dtbo
        cd AnyKernel
        zip -r9 "../${{ github.event.inputs.ZIP_NAME }}-${{ steps.props.outputs.date }}.zip" * -x .git README.md *placeholder
        
    - name: Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: |
          /home/runner/work/myKernel/*.zip
          /home/runner/work/myKernel/build.log
        name: Compiled Kernel for ${{ github.event.inputs.DEVICE_NAME }} - ${{ steps.props.outputs.date }}
        draft: false
        prerelease: false
        tag: ${{ github.run_id }}-${{ steps.props.outputs.date }}
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          ## Notes
            - Flash your newly built kernel!
            - Include building logs.

    - name: Link of Release
      run: |
        echo "Enjoy your Newly Built Kernel"
        echo "https://github.com/${GITHUB_REPOSITORY}/releases/tag/${{ github.run_id }}-${{ steps.props.outputs.date }}"
